Traducimos mensajes y renombramos archivos

diff --git a/.github/workflows/release-build-and-upload.yml b/.github/workflows/release-build-and-upload.yml
--- a/.github/workflows/release-build-and-upload.yml
+++ b/.github/workflows/release-build-and-upload.yml
@@ -1,4 +1,4 @@
-name: Build and Release APK
+name: En un release, compilar y subir el APK
 
 on:
   release:
@@ -14,16 +14,16 @@ jobs:
     runs-on: ubuntu-latest
     environment: Produccion
     steps:
-    - name: Checkout code
+    - name: Checkout del codigo
       uses: actions/checkout@v4
 
-    - name: Set up JDK 17
+    - name: Setup de JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
 
-    - name: Cache Gradle packages
+    - name: Cache de packages de Gradle
       uses: actions/cache@v4
       with:
         path: |
@@ -33,33 +33,25 @@ jobs:
         restore-keys: |
           ${{ runner.os }}-gradle-
 
-    - name: Grant execute permission for gradlew
+    - name: Damos permisos al gradlew
       run: chmod +x gradlew
 
-    - name: Decode keystore
+    - name: Decodificamos keystore
       run: |
         if [ ! -z "$KEYSTORE" ]; then
           echo "$KEYSTORE" | base64 --decode > keystore.jks
-          echo "Keystore decoded successfully"
+          echo "Keystore decodificada"
         else
-          echo "Keystore or signing credentials not found, skipping keystore decode"
+          echo "ERROR: No se encontro keystore en variable de entorno!"
+          exit 1
         fi
       env:
         KEYSTORE: ${{ secrets.KEYSTORE }}
 
-    - name: Build debug APK
+    - name: Compilamos debug APK
       run: ./gradlew assembleDebug
 
-    - name: Build release APK
-      run: ./gradlew assembleRelease
-      env:
-        KEYSTORE: ${{ secrets.KEYSTORE }}
-        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
-        # PKCS12 stores don't allow different passwords
-        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
-        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
-
-    - name: Upload debug APK to release
+    - name: Subimos APK debug al Github release
       run: |
         cp ./app/build/outputs/apk/debug/app-debug.apk ./DonadorAutomatico-debug-${{ github.event.release.tag_name }}.apk
         gh release upload ${{ github.event.release.tag_name }} \
@@ -70,7 +62,16 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       if: github.event.release.tag_name != null
 
-    - name: Upload release APK to release
+    - name: Compilamos release APK
+      run: ./gradlew assembleRelease
+      env:
+        KEYSTORE: ${{ secrets.KEYSTORE }}
+        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
+        # PKCS12 stores don't allow different passwords
+        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
+        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
+
+    - name: Subimos APK de release al Github release
       run: |
         cp ./app/build/outputs/apk/release/app-release.apk ./DonadorAutomatico-${{ github.event.release.tag_name }}.apk
         gh release upload ${{ github.event.release.tag_name }} \
